### ISSUE TITLE
Code the Scraping

### ISSUE THREAD

**Issue by marymiller1954** [contygm/BubbleBust#5]

**Comment by tsg1204** [comment]
made a test with 3 news APIs (the Gardian, BBC, CNN)
https://github.com/tsg1204/pr3newsAPIs

**Comment by marymiller1954** [comment]
Looks great Tatiana!

**Comment by tsg1204** [comment]
it's not only political news just top headlines... if we want only politic,
we'll have to get API's from the site we need to use, bc scraping manually
too long and I keep trying to scrape CNN and can' get it to work...

I'll research more and try scraping API's, couldn't make one of them to
work though yet... will see :)

**Comment by tsg1204** [comment]
Scraping is working, continue on the implementation scraper with API's; working on saving articles to DB

**Comment by tsg1204** [comment]
scraping completed :)
